#!/bin/bash

# hide "last login" line when starting a new terminal session
touch $HOME/.hushlogin

#install zsh
echo 'install oh-my-zhs'
echo '-----------------'
rm -rf $HOME/.oh-my-zsh
curl -L https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh | sh
chsh -s $(which zsh)

#symlink bash_profile
rm $HOME/.bash_profile
ln -s $HOME/.dotfiles/shell/.bash_profile $HOME/.bash_profile

#symlink profile
rm $HOME/.profile
ln -s $HOME/.dotfiles/shell/.bash_profile $HOME/.profile

#symlink yarnrc
rm $HOME/.yarnrc
ln -s $HOME/.dotfiles/shell/.yarnrc $HOME/.yarnrc

#symlink zsh prefs
rm $HOME/.zshrc
ln -s $HOME/.dotfiles/shell/.zshrc $HOME/.zshrc

echo 'Install homebrew'
echo '----------------'
echo install homebrew
sudo rm -rf /usr/local/Cellar /usr/local/.git && brew cleanup
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"

echo 'install composer'
echo '------------'
brew install composer

echo 'install git'
echo '------------'
brew install git

#global git config
ln -s $HOME/.dotfiles/shell/.gitconfig $HOME/.gitconfig

#global gitigore
ln -s $HOME/.dotfiles/shell/.global-gitignore $HOME/.global-gitignore
git config --global core.excludesfile $HOME/.global-gitignore

echo 'install wget'
echo '------------'
brew install wget --overwrite

echo 'install z'
echo '-------------'
brew install z

#activate z
cd ~/.dotfiles/shell
chmod +x z.sh

echo 'Install zsh-autosuggestions'
echo '---------------------------'
brew install zsh-autosuggestions

echo 'install laravel envoy'
echo '---------------------'
composer global require "laravel/envoy=dev-master";

echo 'install laravel installer'
echo '--------------------'
composer global require "laravel/installer";

echo '++++++++++++++++++++++++++++++'
echo '++++++++++++++++++++++++++++++'
echo 'All done!'
echo 'Things to do to make the agnoster terminal theme work:'
echo '1. Install menlo patched font included in ~/.dotfiles/misc https://gist.github.com/qrush/1595572/raw/Menlo-Powerline.otf'
echo '2. Install patched solarized theme included in ~/.dotfiles/misc'

echo '++++++++++++++++++++++++++++++'
echo 'Some optional tidbits'

echo '1. Make sure dropbox is running first. If you have not backed up via Mackup yet, then run `mackup backup` to symlink preferences for a wide collection of apps to your dropbox. If you already had a backup via mackup run `mackup restore` You'\''ll find more info on Mackup here: https://github.com/lra/mackup.'
echo '2. Set some sensible os x defaults by running: $HOME/.dotfiles/macos/set-defaults.sh'
echo '3. Make a .dotfiles-custom/shell/.aliases for your personal commands'

echo '++++++++++++++++++++++++++++++'
echo '++++++++++++++++++++++++++++++'
